import { Octokit } from '@octokit/rest';
import {
  generateFingerprint,
  getFingerprintTag,
  extractExistingFindings,
  filterNewFindings,
  isSameFinding
} from './fingerprint.js';

const SUMMARY_TAG = '<!-- ai-pr-reviewer-summary -->';

const SEVERITY_ICONS = {
  CRITICAL: '🚨 **CRITICAL**',
  HIGH: '⚠️ **HIGH**',
  MEDIUM: '🟡 **MEDIUM**',
  LOW: '🔵 **LOW**'
};

const RISK_BADGES = {
  CRITICAL: '🔴 CRITICAL RISK',
  HIGH: '🟠 HIGH RISK',
  MEDIUM: '🟡 MEDIUM RISK',
  LOW: '🟢 LOW RISK'
};

/**
 * Formats an inline review comment with metadata and fingerprint tag
 */
export function formatInlineComment(finding) {
  const tag = getFingerprintTag(finding.fingerprint, finding);
  const icon = SEVERITY_ICONS[finding.severity] || finding.severity;
  const isBusinessImpact = finding.issue_type === 'POTENTIAL_BUSINESS_IMPACT';
  const ruleLabel = finding.rule_id ? ` | **Rule**: \`${finding.rule_id}\`` : '';

  let body = `${tag}\n`;
  body += `### 🤖 AI Review: ${icon} — ${finding.title}\n\n`;
  body += `**Category**: \`${finding.category}\`${ruleLabel} | **Type**: \`${isBusinessImpact ? 'Business Logic Impact' : 'Definite Issue'}\` | **Confidence**: \`${Math.round(finding.confidence * 100)}%\`\n\n`;
  body += `${finding.description}\n\n`;
  body += `#### 💡 Recommendation\n${finding.recommendation}\n`;

  return body;
}

/**
 * Formats the single dynamically updating PR Summary Dashboard
 */
export function formatSummaryReview({ summary, headSha, activeFindingsCount, resolvedCount = 0, nonInlineFindings = [] }) {
  const badge = RISK_BADGES[summary.risk_level] || summary.risk_level;
  const shortSha = headSha ? headSha.slice(0, 7) : 'latest';

  let md = `${SUMMARY_TAG}\n`;
  md += `## 🤖 Automated AI Code Review Dashboard\n\n`;
  md += `**Latest Analyzed Commit**: \`${shortSha}\` | **Status**: ${badge}\n\n`;
  md += `> ${summary.overview}\n\n`;

  md += `### 📊 Findings Overview\n`;
  md += `| Severity | Active Issues |\n`;
  md += `| :--- | :---: |\n`;
  md += `| 🚨 Critical | **${summary.critical_count}** |\n`;
  md += `| ⚠️ High | **${summary.high_count}** |\n`;
  md += `| 🟡 Medium | **${summary.medium_count}** |\n`;
  md += `| 🔵 Low | **${summary.low_count}** |\n\n`;

  if (resolvedCount > 0) {
    md += `> 🎉 **${resolvedCount}** previously flagged ${resolvedCount === 1 ? 'finding has' : 'findings have'} been **verified as resolved** in commit \`${shortSha}\`.\n\n`;
  }

  if (nonInlineFindings.length > 0) {
    md += `### 📋 General & File-Level Findings\n\n`;
    for (const f of nonInlineFindings) {
      const icon = SEVERITY_ICONS[f.severity] || f.severity;
      const ruleStr = f.rule_id ? ` (\`${f.rule_id}\`)` : '';
      md += `<details>\n<summary>${icon} <b>${f.file}</b>: ${f.title}${ruleStr}</summary>\n\n`;
      md += `**Category**: \`${f.category}\` | **Type**: \`${f.issue_type}\`\n\n`;
      md += `${f.description}\n\n`;
      md += `**Recommendation**:\n${f.recommendation}\n\n`;
      md += `</details>\n\n`;
    }
  }

  md += `---\n`;
  md += `*Review generated by AI PR Review Engine powered by Google Gemini and SonarQube.*`;

  return md;
}

/**
 * Fetches all review threads from GitHub GraphQL API
 */
async function getReviewThreads(octokit, { owner, repo, prNumber }) {
  try {
    const response = await octokit.graphql(
      `
      query GetReviewThreads($owner: String!, $repo: String!, $prNumber: Int!) {
        repository(owner: $owner, name: $repo) {
          pullRequest(number: $prNumber) {
            reviewThreads(first: 100) {
              nodes {
                id
                isResolved
                isOutdated
                path
                line
                comments(first: 10) {
                  nodes {
                    id
                    databaseId
                    body
                    path
                    line
                  }
                }
              }
            }
          }
        }
      }
    `,
      { owner, repo, prNumber }
    );
    return response?.repository?.pullRequest?.reviewThreads?.nodes || [];
  } catch (err) {
    console.warn('Could not fetch review threads via GraphQL:', err.message);
    return [];
  }
}

/**
 * Auto-resolves a review thread on GitHub and posts a resolution reply
 */
async function resolveReviewThread(octokit, { owner, repo, prNumber, thread, headSha }) {
  const threadId = thread.id;
  const firstComment = thread.comments?.nodes?.[0];
  const databaseId = firstComment?.databaseId;
  const shortSha = headSha ? headSha.slice(0, 7) : 'latest';

  console.log(`Resolving review thread ${threadId} (issue fixed in commit ${shortSha})...`);

  // 1. Post resolution reply comment if comment databaseId is available
  if (databaseId) {
    try {
      await octokit.rest.pulls.createReplyForReviewComment({
        owner,
        repo,
        pull_number: prNumber,
        comment_id: databaseId,
        body: `✅ **Resolved in \`${shortSha}\`**: This finding has been addressed and verified.`
      });
    } catch (err) {
      console.warn(`Could not post resolution reply on comment ${databaseId}:`, err.message);
    }
  }

  // 2. Mark thread as resolved in GitHub UI via GraphQL
  try {
    await octokit.graphql(
      `
      mutation ResolveThread($threadId: ID!) {
        resolveReviewThread(input: { threadId: $threadId }) {
          thread {
            id
            isResolved
          }
        }
      }
    `,
      { threadId }
    );
    console.log(`✅ Successfully marked review thread ${threadId} as resolved in GitHub.`);
  } catch (err) {
    console.warn(`Could not resolve review thread ${threadId} via GraphQL:`, err.message);
  }
}

function findClosestValidLine(validLinesSet, targetLine, maxDistance = 5) {
  if (!validLinesSet || validLinesSet.size === 0) return null;
  if (validLinesSet.has(targetLine)) return targetLine;
  let closest = null;
  let minDiff = Infinity;
  for (const line of validLinesSet) {
    const diff = Math.abs(line - targetLine);
    if (diff <= maxDistance && diff < minDiff) {
      minDiff = diff;
      closest = line;
    }
  }
  return closest;
}

/**
 * Publishes the review, manages thread resolutions, and updates the summary dashboard
 */
export async function publishReview({
  context,
  analysisResult,
  githubToken,
  dryRun = false
}) {
  const { prMetadata, files } = context;
  const { summary, findings } = analysisResult;

  if (dryRun || !prMetadata.isPullRequest || !githubToken) {
    console.log('\n================ DRY RUN / LOCAL OUTPUT ================');
    console.log(formatSummaryReview({ summary, headSha: prMetadata.headSha, activeFindingsCount: findings.length }));
    console.log('\n--- Inline Findings ---');
    for (const f of findings) {
      const findingWithFp = { ...f, fingerprint: generateFingerprint(f) };
      console.log(`\nFile: ${f.file}:${f.line}`);
      console.log(formatInlineComment(findingWithFp));
    }
    console.log('========================================================\n');
    return;
  }

  const octokit = new Octokit({ auth: githubToken });
  const { owner, repo, prNumber, headSha } = prMetadata;
  const shortSha = headSha ? headSha.slice(0, 7) : 'commit';

  console.log(`🔍 Inspecting PR #${prNumber} review threads and comments...`);

  // 1. Fetch ALL existing review comments via REST pagination
  let allExistingComments = [];
  try {
    allExistingComments = await octokit.paginate(octokit.rest.pulls.listReviewComments, {
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100
    });
  } catch (err) {
    console.warn('Could not paginate PR review comments:', err.message);
  }

  // 2. Fetch GraphQL review threads for resolution statuses
  const reviewThreads = await getReviewThreads(octokit, { owner, repo, prNumber });

  // Merge thread info into existing comments
  const commentsWithThreadInfo = [...allExistingComments];
  for (const thread of reviewThreads) {
    for (const comment of thread.comments?.nodes || []) {
      const existingMatch = commentsWithThreadInfo.find((c) => (c.id === comment.databaseId || c.node_id === comment.id));
      if (existingMatch) {
        existingMatch.threadId = thread.id;
        existingMatch.isResolved = thread.isResolved;
      } else {
        commentsWithThreadInfo.push({
          id: comment.databaseId,
          node_id: comment.id,
          threadId: thread.id,
          isResolved: thread.isResolved,
          body: comment.body,
          path: comment.path,
          line: comment.line
        });
      }
    }
  }

  const existingFindings = extractExistingFindings(commentsWithThreadInfo);
  const processedFindings = filterNewFindings(findings, existingFindings);

  // 3. Auto-resolve review threads for issues fixed in this push
  let resolvedCount = 0;
  const modifiedFilesSet = new Set(files.map((f) => f.newPath));

  for (const thread of reviewThreads) {
    if (thread.isResolved) continue; // Already resolved

    const firstComment = thread.comments?.nodes?.[0];
    if (!firstComment) continue;

    const threadPath = thread.path || firstComment.path;
    // Only attempt auto-resolution if the file was actually modified in this PR/push
    if (threadPath && modifiedFilesSet.has(threadPath)) {
      const isStillPresent = processedFindings.some((f) => isSameFinding(f, firstComment));
      if (!isStillPresent) {
        await resolveReviewThread(octokit, { owner, repo, prNumber, thread, headSha });
        resolvedCount++;
      }
    }
  }

  // 4. Map diff lines to valid positions for new inline comments
  const validFileLinesMap = new Map();
  for (const file of files) {
    const linesSet = new Set(file.hunkLines && file.hunkLines.length > 0 ? file.hunkLines : file.changedLines);
    validFileLinesMap.set(file.newPath, linesSet);
  }

  const inlineCommentsToPost = [];
  const nonInlineFindings = [];

  for (const finding of processedFindings) {
    const validLines = validFileLinesMap.get(finding.file);
    const resolvedLine = validLines ? findClosestValidLine(validLines, finding.line, 5) : null;

    if (finding.isNew) {
      if (resolvedLine !== null) {
        inlineCommentsToPost.push({
          path: finding.file,
          line: resolvedLine,
          side: 'RIGHT',
          body: formatInlineComment({ ...finding, line: resolvedLine })
        });
      } else {
        nonInlineFindings.push(finding);
      }
    } else {
      console.log(`Skipping already reported finding on ${finding.file}:${finding.line}.`);
    }
  }

  // 5. Update the single dynamic PR Summary Dashboard Comment
  const summaryBody = formatSummaryReview({
    summary,
    headSha,
    activeFindingsCount: findings.length,
    resolvedCount,
    nonInlineFindings
  });

  try {
    const issueComments = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100
    });

    const existingSummary = issueComments.data.find(
      (c) => c.body && c.body.includes(SUMMARY_TAG)
    );

    if (existingSummary) {
      console.log(`Updating existing AI Review summary comment (ID: ${existingSummary.id})...`);
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingSummary.id,
        body: summaryBody
      });
      console.log('✅ Updated existing PR Summary Dashboard comment.');
    } else {
      console.log('Creating initial AI Review summary comment...');
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body: summaryBody
      });
      console.log('✅ Created PR Summary Dashboard comment.');
    }
  } catch (err) {
    console.warn('Could not update/create PR issue summary comment:', err.message);
  }

  // 6. Submit GitHub PR Review (Inline comments & review state)
  let reviewEvent = 'COMMENT';
  if (summary.recommendation === 'REQUEST_CHANGES' && (summary.critical_count > 0 || summary.high_count > 0)) {
    reviewEvent = 'REQUEST_CHANGES';
  } else if (summary.recommendation === 'APPROVE' && summary.critical_count === 0 && summary.high_count === 0) {
    reviewEvent = 'APPROVE';
  }

  if (inlineCommentsToPost.length > 0) {
    console.log(`Submitting GitHub Pull Request Review (event: ${reviewEvent}, new inline comments: ${inlineCommentsToPost.length})...`);
    try {
      await octokit.rest.pulls.createReview({
        owner,
        repo,
        pull_number: prNumber,
        commit_id: headSha,
        event: reviewEvent,
        body: `### 🤖 AI Code Review Findings on \`${shortSha}\`\n\nIdentified **${inlineCommentsToPost.length}** new ${inlineCommentsToPost.length === 1 ? 'item' : 'items'} to address. See inline comments below.`,
        comments: inlineCommentsToPost
      });
      console.log('✅ AI Code Review inline comments submitted via batch review.');
    } catch (err) {
      console.warn(`Batch createReview failed (${err.message}). Retrying individual comments for resilience...`);
      let postedIndividualCount = 0;
      for (const item of inlineCommentsToPost) {
        try {
          await octokit.rest.pulls.createReviewComment({
            owner,
            repo,
            pull_number: prNumber,
            commit_id: headSha,
            path: item.path,
            line: item.line,
            side: item.side || 'RIGHT',
            body: item.body
          });
          postedIndividualCount++;
        } catch (singleErr) {
          console.warn(`Could not post inline comment on ${item.path}:${item.line}:`, singleErr.message);
        }
      }
      console.log(`✅ Posted ${postedIndividualCount}/${inlineCommentsToPost.length} inline comments individually.`);
      try {
        await octokit.rest.pulls.createReview({
          owner,
          repo,
          pull_number: prNumber,
          commit_id: headSha,
          event: reviewEvent,
          body: `### 🤖 AI Code Review Findings on \`${shortSha}\`\n\nIdentified **${postedIndividualCount}** new ${postedIndividualCount === 1 ? 'item' : 'items'} to address.`
        });
      } catch (reviewErr) {
        console.warn('Could not finalize review event status:', reviewErr.message);
      }
    }
  } else if (reviewEvent === 'APPROVE') {
    console.log('All findings resolved or zero findings detected. Submitting APPROVAL review...');
    try {
      await octokit.rest.pulls.createReview({
        owner,
        repo,
        pull_number: prNumber,
        commit_id: headSha,
        event: 'APPROVE',
        body: `### 🤖 AI Code Review: ✅ Approved on \`${shortSha}\`\n\nAll quality, security, and performance standards satisfied.`
      });
      console.log('✅ Approved PR Review submitted.');
    } catch (err) {
      console.warn('Could not submit approval review:', err.message);
    }
  } else {
    console.log(`No new inline comments to post on commit \`${shortSha}\`. Summary dashboard updated.`);
  }
}
