import { Octokit } from '@octokit/rest';
import {
  generateFingerprint,
  getFingerprintTag,
  extractExistingFingerprints,
  filterNewFindings
} from './fingerprint.js';

const SEVERITY_ICONS = {
  CRITICAL: '🚨 **CRITICAL**',
  HIGH: '⚠️ **HIGH**',
  MEDIUM: '🟡 **MEDIUM**',
  LOW: '🔵 **LOW**'
};

const RISK_BADGES = {
  CRITICAL: '🔴 CRITICAL RISK',
  HIGH: '🟠 HIGH RISK',
  MEDIUM: '🟡 MEDIUM RISK',
  LOW: '🟢 LOW RISK'
};

/**
 * Formats an inline review comment with metadata and fingerprint tag
 */
export function formatInlineComment(finding) {
  const tag = getFingerprintTag(finding.fingerprint);
  const icon = SEVERITY_ICONS[finding.severity] || finding.severity;
  const isBusinessImpact = finding.issue_type === 'POTENTIAL_BUSINESS_IMPACT';

  let body = `${tag}\n`;
  body += `### 🤖 AI Review: ${icon} — ${finding.title}\n\n`;
  body += `**Category**: \`${finding.category}\` | **Type**: \`${isBusinessImpact ? 'Business Logic Impact' : 'Definite Issue'}\` | **Confidence**: \`${Math.round(finding.confidence * 100)}%\`\n\n`;
  body += `${finding.description}\n\n`;
  body += `#### 💡 Recommendation\n${finding.recommendation}\n`;

  return body;
}

/**
 * Formats the overall PR Summary Review body
 */
export function formatSummaryReview({ summary, findings, nonInlineFindings = [] }) {
  const badge = RISK_BADGES[summary.risk_level] || summary.risk_level;

  let md = `## 🤖 Automated AI Code Review Summary\n\n`;
  md += `### Overall Assessment: ${badge}\n\n`;
  md += `> ${summary.overview}\n\n`;

  md += `| Severity | Count |\n`;
  md += `| :--- | :---: |\n`;
  md += `| 🚨 Critical | **${summary.critical_count}** |\n`;
  md += `| ⚠️ High | **${summary.high_count}** |\n`;
  md += `| 🟡 Medium | **${summary.medium_count}** |\n`;
  md += `| 🔵 Low | **${summary.low_count}** |\n\n`;

  if (nonInlineFindings.length > 0) {
    md += `### 📋 General & File-Level Findings\n\n`;
    for (const f of nonInlineFindings) {
      const icon = SEVERITY_ICONS[f.severity] || f.severity;
      md += `<details>\n<summary>${icon} <b>${f.file}</b>: ${f.title}</summary>\n\n`;
      md += `**Category**: \`${f.category}\` | **Type**: \`${f.issue_type}\`\n\n`;
      md += `${f.description}\n\n`;
      md += `**Recommendation**:\n${f.recommendation}\n\n`;
      md += `</details>\n\n`;
    }
  }

  md += `---\n`;
  md += `*Review generated by AI PR Review Engine powered by Google Gemini and SonarQube.*`;

  return md;
}

/**
 * Publishes the review to the GitHub Pull Request
 */
export async function publishReview({
  context,
  analysisResult,
  githubToken,
  dryRun = false
}) {
  const { prMetadata, files } = context;
  const { summary, findings } = analysisResult;

  if (dryRun || !prMetadata.isPullRequest || !githubToken) {
    console.log('\n================ DRY RUN / LOCAL OUTPUT ================');
    console.log(formatSummaryReview({ summary, findings }));
    console.log('\n--- Inline Findings ---');
    for (const f of findings) {
      const findingWithFp = { ...f, fingerprint: generateFingerprint(f) };
      console.log(`\nFile: ${f.file}:${f.line}`);
      console.log(formatInlineComment(findingWithFp));
    }
    console.log('========================================================\n');
    return;
  }

  const octokit = new Octokit({ auth: githubToken });
  const { owner, repo, prNumber, headSha } = prMetadata;

  console.log(`Fetching existing comments for PR #${prNumber} to prevent duplicate reports...`);

  // 1. Fetch existing review comments on the PR for deduplication
  let existingComments = [];
  try {
    const commentsResponse = await octokit.rest.pulls.listReviewComments({
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100
    });
    existingComments = commentsResponse.data;
  } catch (err) {
    console.warn('Could not fetch existing PR review comments:', err.message);
  }

  const existingFingerprints = extractExistingFingerprints(existingComments);
  const processedFindings = filterNewFindings(findings, existingFingerprints);

  // Map files and their valid changed lines for inline commenting
  const validFileLinesMap = new Map();
  for (const file of files) {
    validFileLinesMap.set(file.newPath, new Set(file.changedLines));
  }

  const inlineCommentsToPost = [];
  const nonInlineFindings = [];

  for (const finding of processedFindings) {
    const validLines = validFileLinesMap.get(finding.file);

    // Only post as inline if it is a new finding AND the line is part of the diff
    if (validLines && validLines.has(finding.line)) {
      if (finding.isNew) {
        inlineCommentsToPost.push({
          path: finding.file,
          line: finding.line,
          side: 'RIGHT',
          body: formatInlineComment(finding)
        });
      } else {
        console.log(`Skipping duplicate finding on ${finding.file}:${finding.line} (already reported).`);
      }
    } else {
      nonInlineFindings.push(finding);
    }
  }

  // Determine review event: APPROVE, COMMENT, or REQUEST_CHANGES
  let reviewEvent = 'COMMENT';
  if (summary.recommendation === 'REQUEST_CHANGES' && (summary.critical_count > 0 || summary.high_count > 0)) {
    reviewEvent = 'REQUEST_CHANGES';
  } else if (summary.recommendation === 'APPROVE' && summary.critical_count === 0 && summary.high_count === 0) {
    reviewEvent = 'APPROVE';
  }

  const summaryBody = formatSummaryReview({
    summary,
    findings,
    nonInlineFindings
  });

  console.log(`Submitting GitHub Pull Request Review for PR #${prNumber} (event: ${reviewEvent}, inline comments: ${inlineCommentsToPost.length})...`);

  try {
    await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: prNumber,
      commit_id: headSha,
      event: reviewEvent,
      body: summaryBody,
      comments: inlineCommentsToPost
    });
    console.log('✅ AI Code Review submitted successfully to GitHub PR.');
  } catch (err) {
    console.error('Failed to submit review via createReview, falling back to PR issue comment:', err.message);
    try {
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body: summaryBody
      });
      console.log('✅ Posted summary comment to PR.');
    } catch (commentErr) {
      console.error('Failed to post PR issue comment:', commentErr.message);
    }
  }
}
